### ISSUE TITLE
commit_files: lines_added (removed) might be -

### ISSUE THREAD

**Issue by ulysses4ever** [PRL-PRG/ghgrabber#3]
In `commit_files/airbnb_lottie-web.csv` I see:

```
"hash","added lines","deleted lines","file"
...
"b0ad4c71430fb5c5616982c62e9beec3f3946962",-,-,"build/extension/bodymovin.zxp"
```

The `-` screws up my CSV parser. 

I see `-` happens for binary files where there is no meaningful notion of a line. Can we filter out binary files somehow?

**Comment by ulysses4ever** [comment]
So far, I resort to `sed -i '/,-,-,/d' *.csv `

**Comment by kondziu** [comment]
I don't want to remove these lines, since they can be useful for other projects (having information about which files were modified by a commit is useful, regardless of whether it's binary or not).

I agree though that `-` is not a great way to replace missing information. I can change it to `NA` or keep these fields empty. Which do you think would work best with your parser?

**Comment by ulysses4ever** [comment]
This makes sense, yes. For us, it might make a bit more sense to have empty values (`,,` or `,"",`, whichever feels better to you) instead of dashes but that's not critical as the system on top of a CSV parser we work with can't handle missing values at all, at the moment. So I don't even want to bother you with the regeneration of data for this particular issue. We might end up running `sed` through the whole dataset (private replica of it, of course) anyway because I don't expect support for the NAs in the system coming soon.
